name: displayTodayResult

on:
  schedule:
    - cron: "45 22 * * *"
  workflow_dispatch: #manual trigger from github ui

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run Bot Script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: node ./discordBot/discordBotAction.mjs
