name: displayTodayResult

on:
  schedule:
    - cron: "45 22 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install JS Dependencies
        working-directory: ./discordBot
        run: npm install

      - name: Run Bot Script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          WEB_URL: ${{ secrets.WEB_URL }}
          BACKEND_PASSWORD: ${{secrets.BACKEND_PASSWORD}}
          DISCORD_ACTIVITY_LINK: ${{secrets.DISCORD_ACTIVITY_LINK}}

        run: node ./discordBot/discordBotAction.mjs
